// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var PlayMasterMind$ReactHooksTemplate = require("./PlayMasterMind.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(PlayMasterMind$ReactHooksTemplate.make, { }), "root");

/*  Not a pure module */
