// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");
var Tea_app = require("bucklescript-tea/src-ocaml/tea_app.js");
var Tea_html = require("bucklescript-tea/src-ocaml/tea_html.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var MasterMind$ReactHooksTemplate = require("./MasterMind.bs.js");

function pegToLetter(param) {
  switch (param) {
    case 0 : 
        return "R";
    case 1 : 
        return "G";
    case 2 : 
        return "B";
    case 3 : 
        return "Y";
    case 4 : 
        return "O";
    case 5 : 
        return "P";
    
  }
}

var InvalidLetter = Caml_exceptions.create("PlayMasterMind-ReactHooksTemplate.InvalidLetter");

function letterToPeg(letter) {
  var upperLetter = $$String.uppercase(letter);
  switch (upperLetter) {
    case "B" : 
        return /* Blue */2;
    case "G" : 
        return /* Green */1;
    case "O" : 
        return /* Orange */4;
    case "P" : 
        return /* Purple */5;
    case "R" : 
        return /* Red */0;
    case "Y" : 
        return /* Yellow */3;
    default:
      throw InvalidLetter;
  }
}

var emptyGuess = /* record */[
  /* one */"",
  /* two */"",
  /* three */"",
  /* four */""
];

function init(param) {
  return /* record */[
          /* secret : :: */[
            /* Red */0,
            /* :: */[
              /* Red */0,
              /* :: */[
                /* Green */1,
                /* :: */[
                  /* Green */1,
                  /* [] */0
                ]
              ]
            ]
          ],
          /* currentGuess */emptyGuess,
          /* pastGuesses : [] */0,
          /* gameStatus : Playing */0
        ];
}

function setPeg(currentGuess, index, peg_str) {
  switch (index) {
    case 0 : 
        return /* record */[
                /* one */peg_str,
                /* two */currentGuess[/* two */1],
                /* three */currentGuess[/* three */2],
                /* four */currentGuess[/* four */3]
              ];
    case 1 : 
        return /* record */[
                /* one */currentGuess[/* one */0],
                /* two */peg_str,
                /* three */currentGuess[/* three */2],
                /* four */currentGuess[/* four */3]
              ];
    case 2 : 
        return /* record */[
                /* one */currentGuess[/* one */0],
                /* two */currentGuess[/* two */1],
                /* three */peg_str,
                /* four */currentGuess[/* four */3]
              ];
    case 3 : 
        return /* record */[
                /* one */currentGuess[/* one */0],
                /* two */currentGuess[/* two */1],
                /* three */currentGuess[/* three */2],
                /* four */peg_str
              ];
    default:
      throw InvalidLetter;
  }
}

function calculateGameState(model, score) {
  if ((List.length(model[/* pastGuesses */2]) - 1 | 0) >= 21) {
    return /* Lost */2;
  } else if (score[/* exactMatches */0] === 4) {
    return /* Won */1;
  } else {
    return /* Playing */0;
  }
}

function handleGuess(model) {
  var guess_000 = letterToPeg(model[/* currentGuess */1][/* one */0]);
  var guess_001 = /* :: */[
    letterToPeg(model[/* currentGuess */1][/* two */1]),
    /* :: */[
      letterToPeg(model[/* currentGuess */1][/* three */2]),
      /* :: */[
        letterToPeg(model[/* currentGuess */1][/* four */3]),
        /* [] */0
      ]
    ]
  ];
  var guess = /* :: */[
    guess_000,
    guess_001
  ];
  var score = MasterMind$ReactHooksTemplate.getScore(guess, model[/* secret */0]);
  return /* record */[
          /* secret */model[/* secret */0],
          /* currentGuess */emptyGuess,
          /* pastGuesses : :: */[
            /* record */[
              /* guess */guess,
              /* score */score
            ],
            model[/* pastGuesses */2]
          ],
          /* gameStatus */calculateGameState(model, score)
        ];
}

function update(model, param) {
  if (param) {
    return /* record */[
            /* secret */model[/* secret */0],
            /* currentGuess */setPeg(model[/* currentGuess */1], param[0], param[1]),
            /* pastGuesses */model[/* pastGuesses */2],
            /* gameStatus */model[/* gameStatus */3]
          ];
  } else {
    return handleGuess(model);
  }
}

function blankOption(param) {
  return Tea_html.option$prime(undefined, undefined, /* :: */[
              Tea_html.value(""),
              /* [] */0
            ], /* :: */[
              Tea_html.text(""),
              /* [] */0
            ]);
}

function view_peginput(peg_str, n) {
  return Tea_html.select(undefined, undefined, /* :: */[
              Tea_html.onChange(undefined, (function (value) {
                      return /* SetPeg */[
                              n,
                              value
                            ];
                    })),
              /* :: */[
                Tea_html.value(peg_str),
                /* [] */0
              ]
            ], /* :: */[
              blankOption(/* () */0),
              List.map((function (l) {
                      return Tea_html.option$prime(undefined, undefined, /* :: */[
                                  Tea_html.value(l),
                                  /* [] */0
                                ], /* :: */[
                                  Tea_html.text(l),
                                  /* [] */0
                                ]);
                    }), List.map(pegToLetter, MasterMind$ReactHooksTemplate.codePegs))
            ]);
}

function view_enterguess(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              view_peginput(model[/* currentGuess */1][/* one */0], 0),
              /* :: */[
                view_peginput(model[/* currentGuess */1][/* two */1], 1),
                /* :: */[
                  view_peginput(model[/* currentGuess */1][/* three */2], 2),
                  /* :: */[
                    view_peginput(model[/* currentGuess */1][/* four */3], 3),
                    /* :: */[
                      Tea_html.button(undefined, undefined, /* :: */[
                            Tea_html.onClick(/* Guess */0),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.text("Guess"),
                            /* [] */0
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

function view_won(model) {
  var numGuesses = List.length(model[/* pastGuesses */2]);
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("You won!"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.text("It took you " + (String(numGuesses) + " guesses")),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]);
}

function view_lost(param) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Sorry, you lost :("),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function view_enterguess_or_winlose(model) {
  var match = model[/* gameStatus */3];
  switch (match) {
    case 0 : 
        return view_enterguess(model);
    case 1 : 
        return view_won(model);
    case 2 : 
        return view_lost(model);
    
  }
}

function view_pastguess(pastGuess) {
  var guess = pastGuess[/* guess */0];
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.text(pegToLetter(List.nth(guess, 0))),
              /* :: */[
                Tea_html.text(pegToLetter(List.nth(guess, 1))),
                /* :: */[
                  Tea_html.text(pegToLetter(List.nth(guess, 2))),
                  /* :: */[
                    Tea_html.text(pegToLetter(List.nth(guess, 3))),
                    /* :: */[
                      Tea_html.text(" SCORE: "),
                      /* :: */[
                        Tea_html.text("exact: " + String(pastGuess[/* score */1][/* exactMatches */0])),
                        /* :: */[
                          Tea_html.text(" partial: " + String(pastGuess[/* score */1][/* colorMatches */1])),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function view_pastguesses(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, List.map(view_pastguess, model[/* pastGuesses */2]));
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.header(undefined, undefined, /* :: */[
                    Tea_html.style("text-align", "center"),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.h1(undefined, undefined, /* [] */0, /* :: */[
                          Tea_html.text("MasterMind!"),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]),
              /* :: */[
                view_enterguess_or_winlose(model),
                /* :: */[
                  view_pastguesses(model),
                  /* [] */0
                ]
              ]
            ]);
}

var partial_arg_000 = /* model : record */[
  /* secret : :: */[
    /* Red */0,
    /* :: */[
      /* Red */0,
      /* :: */[
        /* Green */1,
        /* :: */[
          /* Green */1,
          /* [] */0
        ]
      ]
    ]
  ],
  /* currentGuess */emptyGuess,
  /* pastGuesses : [] */0,
  /* gameStatus : Playing */0
];

var partial_arg = /* record */[
  partial_arg_000,
  /* update */update,
  /* view */view
];

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

var maxGuesses = 21;

exports.pegToLetter = pegToLetter;
exports.InvalidLetter = InvalidLetter;
exports.letterToPeg = letterToPeg;
exports.emptyGuess = emptyGuess;
exports.init = init;
exports.maxGuesses = maxGuesses;
exports.setPeg = setPeg;
exports.calculateGameState = calculateGameState;
exports.handleGuess = handleGuess;
exports.update = update;
exports.blankOption = blankOption;
exports.view_peginput = view_peginput;
exports.view_enterguess = view_enterguess;
exports.view_won = view_won;
exports.view_lost = view_lost;
exports.view_enterguess_or_winlose = view_enterguess_or_winlose;
exports.view_pastguess = view_pastguess;
exports.view_pastguesses = view_pastguesses;
exports.view = view;
exports.main = main;
/* Tea_html Not a pure module */
