// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Tea_app = require("bucklescript-tea/src-ocaml/tea_app.js");
var Tea_html = require("bucklescript-tea/src-ocaml/tea_html.js");

function init(param) {
  return /* record */[
          /* secret : :: */[
            /* Red */0,
            /* :: */[
              /* Red */0,
              /* :: */[
                /* Green */1,
                /* :: */[
                  /* Green */1,
                  /* [] */0
                ]
              ]
            ]
          ],
          /* guesses : [] */0
        ];
}

function update(model, param) {
  return model;
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.text("Welcome to MasterMind!"),
              /* [] */0
            ]);
}

var partial_arg_000 = /* model : record */[
  /* secret : :: */[
    /* Red */0,
    /* :: */[
      /* Red */0,
      /* :: */[
        /* Green */1,
        /* :: */[
          /* Green */1,
          /* [] */0
        ]
      ]
    ]
  ],
  /* guesses : [] */0
];

var partial_arg = /* record */[
  partial_arg_000,
  /* update */update,
  /* view */view
];

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

exports.init = init;
exports.update = update;
exports.view = view;
exports.main = main;
/* Tea_html Not a pure module */
